/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryName = IDL.Text;
export const Category = IDL.Record({
  'name' : CategoryName,
  'words' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const GameSession = IDL.Principal;
export const PuzzleTime = IDL.Record({
  'timestamp' : Time,
  'sessionId' : GameSession,
  'timeTaken' : Time,
});

export const idlService = IDL.Service({
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(CategoryName)], ['query']),
  'getLeaderboard' : IDL.Func([CategoryName], [IDL.Vec(PuzzleTime)], ['query']),
  'getPuzzle' : IDL.Func([CategoryName], [Category], ['query']),
  'init' : IDL.Func([], [], []),
  'submitPuzzleTime' : IDL.Func([CategoryName, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryName = IDL.Text;
  const Category = IDL.Record({
    'name' : CategoryName,
    'words' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const GameSession = IDL.Principal;
  const PuzzleTime = IDL.Record({
    'timestamp' : Time,
    'sessionId' : GameSession,
    'timeTaken' : Time,
  });
  
  return IDL.Service({
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(CategoryName)], ['query']),
    'getLeaderboard' : IDL.Func(
        [CategoryName],
        [IDL.Vec(PuzzleTime)],
        ['query'],
      ),
    'getPuzzle' : IDL.Func([CategoryName], [Category], ['query']),
    'init' : IDL.Func([], [], []),
    'submitPuzzleTime' : IDL.Func([CategoryName, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };